### ISSUE TITLE
[2] Make (user-)grafana upgrades work

### ISSUE THREAD

**Issue by OlleLarsson** [elastisys/compliantkubernetes-apps#185]
When we are upgrading grafana, the pod in the new replicaset will be stuck in init-phase becuase the old grafana pod is still running and holding the volume making the new pod unable to start.

```
Events:
  Type     Reason              Age    From                     Message
  ----     ------              ----   ----                     -------
  Normal   Scheduled           9m     default-scheduler        Successfully assigned monitoring/user-grafana-584f4cbfbc-m7xtl to release-test-service-cluster-worker-1
  Warning  FailedAttachVolume  9m1s   attachdetach-controller  Multi-Attach error for volume "pvc-568dd1d4-fcea-4a94-b0dc-8e35ecb3e51c" Volume is already used by pod(s) user-grafana-5f45bb8c48-prnqj
  Warning  FailedMount         6m58s  kubelet                  Unable to attach or mount volumes: unmounted volumes=[storage], unattached volumes=[sc-dashboard-provider storage user-grafana-token-8g745 sc-dashboard-volume config]: timed out waiting for the condition
  Warning  FailedMount         4m45s  kubelet                  Unable to attach or mount volumes: unmounted volumes=[storage], unattached volumes=[storage user-grafana-token-8g745 sc-dashboard-volume config sc-dashboard-provider]: timed out waiting for the condition
  Warning  FailedMount         2m27s  kubelet                  Unable to attach or mount volumes: unmounted volumes=[storage], unattached volumes=[sc-dashboard-volume config sc-dashboard-provider storage user-grafana-token-8g745]: timed out waiting for the condition
  Warning  FailedMount         9s     kubelet                  Unable to attach or mount volumes: unmounted volumes=[storage], unattached volumes=[user-grafana-token-8g745 sc-dashboard-volume config sc-dashboard-provider storage]: timed out waiting for the condition
```

DOD: it is possible to upgrade grafana without manual intervention.

**Comment by tordsson** [comment]
Simply solved by not doing rolling upgrades? Can this be upstreamed?

**Comment by cristiklein** [comment]
This might be fixed in the latest version of the Chart: https://github.com/grafana/helm-charts/commit/855fde1551e5f9f9e42940bdf9ddd41574cee643

**Comment by lentzi90** [comment]
This can easily be solved by setting `spec.strategy=Recreate` ([docs](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy)) [here in the values](https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L34).
However, I would argue that a better solution for applications like grafana is to use RWX volumes, since this would allow us to scale it and avoid disruptions (#198 ). We could set up nfs-server-provisioner on top of a normal PVC, which would then allow multiple Pods to mount it. I'm not completely sure about how grafana handles multiple replicas but I'm guessing that the state stored in the volume is basically just json files and perhaps an SQLite DB.

The update that Cristian linked (support for StatefulSet) makes me curious though. Have they added some kind of clustering logic for grafana? Or does it only support a StatefulSet with a single replica? If that's the case I don't see the difference really between StatefulSet and Deployment with `spec.strategy=Recreate`.

**Comment by cristiklein** [comment]
My understanding is that the upstream Grafana Helm Chart encourages either a stateless Grafana as a Deployment, or stateful Grafana as a StatefulSet. Other options are, of course, possible by changing values. I would either stick to these two options, or understand *why* upstream chose this dichotomy. I'm suspecting that it might have to do with RWX volumes not being widely supported: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes

**Comment by lentzi90** [comment]
NFS supports RWX, that was why I suggested it.

> My understanding is that the upstream Grafana Helm Chart encourages either a stateless Grafana as a Deployment, or stateful Grafana as a StatefulSet.

Where did you get this from? It looks to me like the default is a stateless Deployment, but it is a smaller change to the values to just enable persistence using PVC, than to switch to a StatefulSet.

I'm fine with a StatefulSet also, but I'm questioning the motive to switch. If Grafana doesn't have any built in clustering logic a StatefuleSet is sort of more dangerous than a Deployment since it will be *possible* to scale it, but then each replica will have its own state. So if you happen to save your dashboard on replica 1 it won't be available on replica 2. With a Deployment and RWO PVC as we have now, this is impossible as only a single Pod can mount the volume.
So if the only reason to switch to a StatefulSet is to get the "scale down completely" behavior when updating, then I think it makes more sense to use a Deployment with `spec.strategy=Recreate` (which is easy to set in the values).

**Comment by cristiklein** [comment]
> NFS supports RWX, that was why I suggested it.
> 
> > My understanding is that the upstream Grafana Helm Chart encourages either a stateless Grafana as a Deployment, or stateful Grafana as a StatefulSet.
> 
> Where did you get this from? It looks to me like the default is a stateless Deployment, but it is a smaller change to the values to just enable persistence using PVC, than to switch to a StatefulSet.

It seems to me that Deployment is automatically disabled when PVC persistence is enabled:

- https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/deployment.yaml#L1

Am I missing something? (My brain's `helm template` might be off. :joy:)

**Comment by OlleLarsson** [comment]
> It seems to me that Deployment is automatically disabled when PVC persistence is enabled:
> 
> * https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/deployment.yaml#L1
> 
> Am I missing something? (My brain's `helm template` might be off. )

```
{{ if (or (not .Values.persistence.enabled) (eq .Values.persistence.type "pvc")) }} --> {{ if (or (not true) (true)) }} --> {{ if (true)) } --> {{ true }}
```

**Comment by cristiklein** [comment]
```
$ helm template . --set persistence.enabled=true | egrep '(Deployment|State|Persist)'
kind: PersistentVolumeClaim
kind: Deployment
$ helm template .  | egrep '(Deployment|State|Persist)'
kind: Deployment
```

Please file a bug against my in-brain `helm template`. :smile:

Okay, but do I get correctly that this is a bug in the upstream Helm Chart. If `persistence.enabled==true` and `persistence.type==pvc`, then `spec.strategy==Recreate`. If so, can someone file a bug against the upstream Chart? I see two options:

1. Add validation in the Helm Chart (see [example here](https://github.com/bitnami/charts/blob/master/bitnami/external-dns/templates/_helpers.tpl#L269))
2. Set `spec.strategy` to `Recreate` is `spec.strategy` is unset and `persistence.enabled==true`.

**Comment by Xartos** [comment]
https://github.com/grafana/helm-charts/issues/146

**Comment by lentzi90** [comment]
I think it would be a bit more complicated:
If `persistence.enabled==true` and `persistence.type==pvc` and `persistence.accessModes` contains `ReadWriteOnce`,
then `spec.strategy==Recreate`.

But then again, with logic like this built in, I think it should also have:
If `persistence.enabled==true`, then `replicas==1` or `replicas==0`.

At that point I would also start to wonder about things like ports (hard coded to 3000 in [the pod](https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/_pod.tpl#L308), but possible to change in the readiness probe and service. And then I just want to stop and forget about it all. :slightly_frowning_face:

**Comment by cristiklein** [comment]
> I think it would be a bit more complicated:
> If `persistence.enabled==true` and `persistence.type==pvc` and `persistence.accessModes` contains `ReadWriteOnce`,
> then `spec.strategy==Recreate`.
> 
> But then again, with logic like this built in, I think it should also have:
> If `persistence.enabled==true`, then `replicas==1` or `replicas==0`.

Excellent! Please codify this knowledge in a nice validation within the Helm Chart.

> 
> At that point I would also start to wonder about things like ports (hard coded to 3000 in [the pod](https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/_pod.tpl#L308), but possible to change in the readiness probe and service. And then I just want to stop and forget about it all.

This is out-of-scope for the current issue. Let's cross that bridge when we are at it.

**Comment by cristiklein** [comment]
Fixed by #272

**Comment by villesau** [comment]
@cristiklein I'm still getting `Multi-Attach error for volume` error with Grafana helm deployment on GKE.

**Comment by cristiklein** [comment]
@villesau Can you give us more information, like the output of:

```
kubectl get -n monitoring deployment,statefulset,pods,pvc -o yaml
helm ls -n monitoring
```

?

**Comment by grtrout** [comment]
So I am gathering that the accepted fix here is to set the deployment strategy to Recreate, like this:

```
deploymentStrategy:
  type: Recreate
```

But is there any benefit to doing that versus setting it to be a StatefulSet instead of a Deployment? I feel like doing this is cleaner, but maybe I am missing something. Can anyone provide some insight on pros/cons for these two changes?
```
persistence:
  type: statefulset
```

**Comment by cristiklein** [comment]
@grtrout As long as `replicas: 1`, I assume the two solutions are roughly equivalent. I favour `Deployment` over `StatefulSet`, since `StatefulSet` tends to be a bit too "careful" in certain cases. For example, when a [Node dies](https://github.com/kubernetes/kubernetes/issues/74689) StatefulSet needs a lot more convincing before recreating the Pod on another Node.

**Comment by villesau** [comment]
@cristiklein I don't anymore remember how I got rid of the error, but I suspect it might've been this config that I added:

```
persistence:
  enabled: true
  storageClassName: "standard"
deploymentStrategy: { "type": "Recreate" }
```

**Comment by cristiklein** [comment]
@villesau We ended up with exactly that solution in Compliant Kubernetes:

https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/values/grafana-user.yaml.gotmpl#L12-L13
https://github.com/elastisys/compliantkubernetes-apps/blob/main/helmfile/values/grafana-user.yaml.gotmpl#L33-L38
